[pytest]
testpaths = tests
addopts = --html=reports/report.html --self-contained-html -v
markers =
    smoke: mark test as part of the smoke testing suite
    regression: mark test as part of the regression testing suite
